config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'artists#index'

  get '/get_states_by_country_name', to: 'application#get_states_by_country_name'
  get 'artists/profile', to: 'artists#profile', as: :artist_profile
  get 'artists/edit_profile', to: 'artists#edit_profile', as: :edit_profile
  patch 'artists/update_profile', to: 'artists#update_profile', as: :update_profile
  post 'artists/upload_paintings', to: 'artists#upload_paintings', as: :upload_paintings
  post 'artists/mark_public', to: 'artists#mark_public', as: :mark_public

end

app/models/painting.rb
class Painting < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

   	validates :name, presence: true
   	validates :email, format:{with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "is badly formatted "}, uniqueness: true
   	validates :phone, numericality: { only_integer: true }, :allow_blank => true

 	has_many :paintings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # layout 'cyborg'
  layout :layout

  before_action :configure_permitted_parameters, if: :devise_controller?

	def get_states_by_country_name
	    states = {}
	    begin     
	      @country = ISO3166::Country[params[:country_val]]
	      @country.states.each {|key, value| 
	        if value['name']!=nil
	          states[key] = value['name']
	        end
	  
	            } if @country
	    rescue
	      nil
	    end
	    render json: states, status: :ok
	end



	protected
		def layout
		    # only turn it off for login pages:
		    # is_a?(Devise::SessionsController) ? false : "cyborg"
		    # or turn layout off for every devise controller:
		    devise_controller? ? false : "cyborg"
	  	end
	  	
	  	def after_sign_in_path_for(resource)
	    	root_path
	  	end

	  	def configure_permitted_parameters
   		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :phone, :state, :country, :city, :user_name, :image ) }
	  	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :get_object, :only=>[:profile, :edit_profile, :update_profile, :upload_paintings, :mark_public]#common method to get object

	def index
		@users = User.all
	end

	def profile
	end

	def edit_profile
		render :layout=> false
	end

	def update_profile
		saved = @artist.update(update_params)
		password = params[:user][:password]
		if saved
			notice = "Updated Successfully!!"
			unless @artist.valid_password?(password)
				@artist.update(password: password) 
				notice += "\n Please login with your new password!!"
				redirect_to root_path, :notice => notice
			else
				redirect_to artist_profile_path(id: @artist.try(:id)), :notice => notice
			end
		else
			redirect_to artist_profile_path(id: @artist.try(:id)), alert: "Something went wrong!!"
		end
	end

	def upload_paintings
		@artist.paintings.build(painting_params)

		if @artist.save
			redirect_to artist_profile_path(id: @artist.try(:id)), :notice => "Uploaded Successfully!!"
		else
			redirect_to artist_profile_path(id: @artist.try(:id)), :alert => @artist.errors.full_messages.to_sentence
		end
	end

	def mark_public
		painting_params = params[:paintings][:is_public]
		image_ids = painting_params.select{|key, val| key if val == "1" } if painting_params
		private_image_ids = painting_params.select{|key, val| key if val == "0" } if painting_params

		if image_ids.present? || private_image_ids.present?
			paintings = Painting.where(id: image_ids.keys) if image_ids.present?
			private_painting = Painting.where(id: private_image_ids.keys) if private_image_ids.present?
			paintings.update_all(is_public: 1) if paintings.present?
			private_painting.update_all(is_public: 0) if private_painting.present?
		end

		redirect_to artist_profile_path(id: @artist.try(:id)), :notice => "Marked Public Successfully!!"
	end

	private 

	def get_object
		@artist = User.find_by(id: params[:id])

		unless @artist.present?
			redirect_to root_path, alert: "Record not found!!"
		end
	end

	def update_params
		params.require(:user).permit(:id, :name, :email, :country, :state, :phone, :city, :image, :user_name, :about)
	end

	def painting_params
		params.require(:painting).permit(:name, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit_profile.html.erb
<div class="col-sm-6" style="margin-left:300px">
  <div class="span3 well">
    <legend>Edit Artist</legend>

    <%= form_for(@artist, url: update_profile_path(id: @artist.try(:id))) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <%#= devise_error_messages! %>

      <div class="row">
        <div class="col-sm-12">
          <div class="field">
            <%= f.label :name %>*<br />
            <%= f.text_field :name, class: 'form-control', placeholder: "full name", autofocus: true %>

          </div>
        </div>
      </div><br/>
      
      <div class="row">
        <div class="col-sm-12">
          <div class="field">
            <%= f.label :email %>*<br />
            <%= f.email_field :email, class: 'form-control' , placeholder: "enter email", autofocus: true %>
          </div>
         </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-6">
          <div class="field">
            <%= f.label :password %>*
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, class: 'form-control' , placeholder: "password", autocomplete: "off"%>
          </div>
         </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-6">
          <div class="field">
            <%= f.label :country %>*<br />
             <%=f.select :country,  ISO3166::Country.all.sort_alphabetical.collect {|c| [ c.name, c.alpha2 ]}, {:include_blank => '- Select Country -'}, :class=>"form-control", :onchange => 'getStateNames();'%>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="field">
            <%= f.label :state %>*<br />
             <%= f.select :state, {}, {:include_blank => '- Select State -'}, :class=>"form-control" %>
          </div>
         </div>
      </div><br/> 

      <div class="row">
         <div class="col-sm-6">
          <div class="field">
            <%= f.label :phone %>*<br />
            <%= f.text_field :phone,  class: 'form-control', placeholder: "contact number", autofocus: true %>
          </div>
         </div>
         <div class="col-sm-6">
          <div class="field">
            <%= f.label :city %>*<br />
            <%= f.text_field :city,  class: 'form-control', placeholder: "city", autofocus: true %>
          </div>
         </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-8">
          <div class="field">
            <%= f.label :user_name %><br />
            <%= f.text_field :user_name, class: 'form-control', autofocus: true, placeholder: "user name"%>
          </div><br />
         </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-6">
          <div class="field">
            <%= f.label :image %><br />
            <%= f.file_field :image,  class: 'form-control', placeholder: "contact number", autofocus: true %>
          </div>
         </div>
      </div><br/>

      <div class="row">
        <div class="col-sm-6">
          <div class="field">
            <%= f.label :about %><br />
            <%= f.text_area :about,  class: 'form-control', placeholder: "about", autofocus: true %>
          </div>
         </div>
      </div><br/>

      <div class="actions">
        <%= f.submit "Update", class: 'btn btn-warning'%>
        <%#= link_to "Cancel","/", class: "btn btn-secondary"%>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div><br />
    <% end %>
    <%#= render "devise/shared/links" %>
  </div>
</div>

<script type="text/javascript">

  $('#edit_user').validate({ // initialize the plugin
    rules: {
      "user[name]": {required: true},
      "user[email]": {required: true},
      "user[password]": {required: true},
      "user[country]": {required: true},
      "user[state]": {required: true},
      "user[city]": {required: true},
      "user[phone]": {required: true},
    },
  });

  jQuery.extend(jQuery.validator.messages, {
    equalTo: "Doesn't match with password!!"
  });

  $("#user_country").change();

  function getStateNames() {
    var selectedCountry;
    $('#user_state').empty().append($("<option></option>").attr("value", '').text('- Select State -'));
    selectedCountry = $("#user_country option:selected").val();
    if (selectedCountry === "") {return;}
    $.ajax({
      url: "/get_states_by_country_name?country_val=" + selectedCountry,
      type: 'GET',
      success: function (result) {
        $('#user_state').removeClass('hidden');
        $.each(result, function (key, value) {
          $('#user_state').append($("<option></option>").attr("value", key).text(value));
        });
        <%if @artist.state?%>
          $('#user_state').val("<%=@artist.state%>")
        <%end%>
      }
    });
  }

</script>

app/views/artists/index.html.erb
<h2>Artists Dashboard</h2>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <%if @users.empty?%>
                <h3>No Artists Present!!</h3>
            <%else%>
                <%@users.each do |user_obj|%>
                    <div class="col-md-3">
                        <div class="thumbnail" style="height: 200px;">
                            <div style="height: 70%;" align="center">
                                <%= image_tag user_obj.image? ? user_obj.image : 'http://placehold.it/320x200', style: "height: 150px;"%>
                            </div>
                            <div class="caption">
                              <h3 align="center"><%= link_to user_obj.name, artist_profile_path(id: user_obj.id)%></h3>
                            </div>
                        </div>
                    </div>
                <% end %>
            <%end%>
        </div>
    </div>
</div>

app/views/artists/profile.html.erb
<div class="container">    
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading"><h4 >Artist Profile</h4></div>
      <div class="panel-body">
        <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
          <%= image_tag @artist.image.url(:medium) %>
        </div>
        <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
          <div class="container" >
            <h2><%= @artist.name %></h2>
            <h4><%= @artist.about %></h4>
          </div>
          <hr>
          <ul class="container details">                    
            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span><%= @artist.email %></p></li>
            <li><p><span class="glyphicon glyphicon-phone" style="width:50px;"></span><%= @artist.phone %></p></li>
            <li><p><span class="glyphicon glyphicon-map-marker" style="width:50px;"></span><%= ISO3166::Country.find_country_by_alpha2(@artist.country).name if @artist.country?%></p></li>
            <li><p><span class="glyphicon glyphicon-map-marker" style="width:50px;"></span><%= @artist.state %></p></li>
          </ul>
          <hr>
          <%= link_to "edit profile", edit_profile_path(id: @artist.id), :class => "btn btn-info", "data-toggle" => "modal", "data-target" => "#edit_profile_modal" if @artist.eql? current_user%>
          	<%= link_to 'Back', "/", class: "btn btn-info"%>
        </div>
      </div>
    </div>
  </div>

  	<!-- modal for user profile -->
  	<div class="modal fade" id="edit_profile_modal" role="dialog">
      <div class="modal-dialog" style="width: 100%;">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add Album</h4>
          </div>
          <div class="modal-body signup_form"></div>
        </div>
      </div>
    </div>

    
    <div class="row">
    	<button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#painting_modal">Add Painting</button>
    </div>
    <div class="row">
        <%if @artist.paintings.empty?%>
            <h3>No Paintings Added!!</h3>
        <%else%>
        	<%= form_for :paintings, url: mark_public_path(id: @artist.id, make_public: true), html: { multipart: true, id: "public_painting_form"} do |f| %>
	            	
	            <% paintins_array = []
	            if @artist.eql? current_user
	            	paintins_array = @artist.paintings
            	else
	            	paintins_array = @artist.paintings.select { |obj| obj.is_public? }
        		end%>
	            <%paintins_array.each do |curr_obj|%>
	                <div class="col-md-3">
	                    <div class="thumbnail" style="height: 200px;">
	                        <div style="height: 70%;" align="center">
	                            <%= image_tag curr_obj.image? ? curr_obj.image : 'http://placehold.it/320x200', style: "height: 150px;"%>
	                        </div>
	                        <div class="caption">
	                        	<div>
		                        	<div style="float: left; width: 50%">
		                          		<h3 align="right">
		                          			<%= curr_obj.name %>
		                          		</h3>
		                          	</div>
		                          	<div style="float: left; width: 50%">
		                            	<%= f.check_box "is_public[#{curr_obj.id}]", checked: curr_obj.is_public, class: 'form-control painting_check', style: "margin: 30px;" if @artist.eql? current_user%>
		                          	</div>
	                          	</div>
	                        </div>
	                    </div>
	                </div>
	            <% end %>

	            <%= f.submit "Apply Changes",class: 'btn btn-primary', style: "display:none", id: "check_submit" %>
            <% end %>
        <%end%>
    </div>

    <!-- for painting upload -->
        <div class="modal fade" id="painting_modal" role="dialog">
		    <div class="modal-dialog">
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal">&times;</button>
		          <h4 class="modal-title">Add Painting</h4>
		        </div>
		        <div class="modal-body">
		          	<%@painting = Painting.new%>
		          	<%= form_for @painting, url: upload_paintings_path(id: @artist.id), html: { multipart: true} do |f| %>
			          	<%= f.label :name, "Painting Name" %>
			          	<%= f.text_field :name, class: 'form-control', :required => true %><br/>
			          	<%= f.label :image, "Painting File" %>
			          	<%= f.file_field :image, class: 'form-control', :required => true %><br/>
			          	<%= f.submit "Add Painting",class: 'btn btn-primary'  %>
			          	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	          		<% end %>        
		        </div>
		      </div>
		    </div>
	  	</div>
	  	<!-- for painting upload -->
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
	var checkBoxes = $('form .painting_check');
	checkBoxes.change(function () {
		$('#check_submit').show();
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindfireApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cyborg.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paintings" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]--></head>

    <%= stylesheet_link_tag "cyborg", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Paintings</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
          </ul>
          <ul class="nav navbar-nav ml-auto" style="float:right">
            <%if !user_signed_in?%>         
              <li class="nav-item"><%= link_to "Login", new_session_path(:user), :class => "btn", "data-toggle" => "modal", "data-target" => "#login_modal" %></li>
              <li class="nav-item"><%= link_to "Sign up", new_registration_path(:user), :class => "btn", "data-toggle" => "modal", "data-target" => "#myModal" %></li>
              <%else%>
                <li class="nav-item"><%= link_to current_user.name, artist_profile_path(id: current_user.id) %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <!-- <li><%#= link_to "Profile", :action => 'profile', :controller => 'users', :id => current_user.id %></li> -->
                    <!-- <li><%#= link_to "Albums", :action => 'album', :controller => 'users' %></li> -->
                    <li><%= link_to('Logout', destroy_user_session_path, method: :delete ) %></li>
                  </ul>
                </li>    
              <%end%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase">
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div style="margin-top: 10%;">
        <%if flash[:notice].present?%>
          <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <%elsif flash[:alert].present?%>
          <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <%end%>
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog" style="width: 100%;">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body signup_form"></div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="login_modal" role="dialog">
          <div class="modal-dialog" style="width: 100%;">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Album</h4>
              </div>
              <div class="modal-body signup_form"></div>
            </div>
          </div>
        </div>

        <%= yield%>
      </div>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "cyborg" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>


    <style type="text/css">
      label.error {
          color: red;
       }
    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <% msg_arr = [] 
      object.errors.full_messages.each do |msg| %>
      <% msg_arr << msg %>
    <% end 
    flash.now[:alert] = msg_arr.uniq.join(",")%>
  </div>
  <% if flash[:alert] %>
    <p id="notice" style="color: red;"><%= flash[:alert] %></p>
  <% end %>
<% end %>